# Generated by Django 2.2.5 on 2019-09-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=100)),
                ('description', models.CharField(default=' ', max_length=1000)),
                ('imageLocation', models.CharField(default=' ', max_length=500)),
                ('vedioLocation', models.CharField(default=' ', max_length=500)),
            ],
            options={
                'db_table': 'placeDb',
            },
        ),
    ]
