# Generated by Django 2.2.5 on 2019-09-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField()),
                ('imageLocation', models.CharField(default=' ', max_length=500)),
                ('status', models.CharField(default=' ', max_length=1000)),
            ],
            options={
                'db_table': 'imageDb',
            },
        ),
        migrations.CreateModel(
            name='VideoLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.IntegerField()),
                ('vedioLocation', models.CharField(default=' ', max_length=500)),
                ('status', models.CharField(default=' ', max_length=1000)),
            ],
            options={
                'db_table': 'vedioDb',
            },
        ),
    ]
