# Generated by Django 2.2.5 on 2019-09-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_imageloc_videoloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapp',
            name='imageLocation',
        ),
        migrations.RemoveField(
            model_name='myapp',
            name='vedioLocation',
        ),
    ]
