# Generated by Django 2.2.5 on 2019-09-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190907_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageloc',
            name='imageLocation',
            field=models.FileField(default=' ', upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='videoloc',
            name='vedioLocation',
            field=models.FileField(default=' ', upload_to='media/vedios/'),
        ),
    ]
