# Generated by Django 2.2.5 on 2019-09-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190907_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='latitude',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='myapp',
            name='longitude',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
