# Generated by Django 2.2.5 on 2019-10-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20191004_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapp',
            name='placetitle2',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='myapp',
            name='placetitle3',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='myapp',
            name='placetitle4',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='myapp',
            name='placevalue2',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='myapp',
            name='placevalue3',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='myapp',
            name='placevalue4',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
