# Generated by Django 2.2.5 on 2019-10-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20191008_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapp',
            name='image_map',
        ),
        migrations.RemoveField(
            model_name='myapp',
            name='video_map',
        ),
    ]
