# Generated by Django 2.2.5 on 2019-10-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20191013_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myapp',
            name='description_status',
        ),
    ]
